apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bi-efs
  namespace: aiip-bi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-bi
  volumeName: bi-pv
  resources:
    requests:
      storage: 5Gi