apiVersion: v1
kind: PersistentVolume
metadata:
  name: bi-pv
  namespace: aiip-bi
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-bi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a43ef4c4
